### ISSUE TITLE
Create Korali-specific docker image

### ISSUE THREAD

**Issue by SergioMartin86** [cselab/korali#445]
Fabian, I'd appreciate your help on this.

**Comment by fab4100** [comment]
I have added a `Dockerfile` in branch `add-docker`.  Tests currently fail due
to issue #451.  This issue must be resolved in order to automate the docker
image build.  Some of the examples in the `korali-apps` do not work.

A docker image could be built nightly and pushed to `cselab/korali` on
dockerhub.com.  A user can then simply `docker pull cselab/korali` to get the
image and use it right away.
